---
title: "Data Wrangling/Processing"
author: "Fiona Price"
date: "2024-11-30"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
library(dplyr)
library(ggplot2)
library(here)
library(tidyverse)
library(readxl)
library(sf)
```

```{r}
#Check file path
here()
#Load in data. Only looking at the fourth sheet.
energy_data <- read_excel(here("./Data/Raw/egrid2022_data.xlsx"), sheet = 4)
#Our table has sub-headers, which we don't need, so we can get rid of that row.
energy_data <- energy_data[-1, ]
```

```{r}
#Find list of all columns
colnames(energy_data)
#Select only the relevant columns
energy_data_selected <- energy_data %>% 
  select('Data Year', 'Plant state abbreviation', 'Plant name', 'Utility name', 
         'Plant county name', 'Plant latitude', 'Plant longitude', 'Number of units',
         'Number of generators', 'Plant primary fuel category', 
         'Plant nameplate capacity (MW)', 'Plant annual net generation (MWh)',
         'Plant annual NOx emissions (tons)', 'Plant annual SO2 emissions (tons)',
         'Plant annual CO2 emissions (tons)', 'Plant annual CH4 emissions (lbs)',
         'Plant annual N2O emissions (lbs)')
```

```{r}
#Select for only NC
NC_energy <- energy_data_selected %>% 
  filter(energy_data_selected$`Plant state abbreviation` == "NC")
```

```{r}
#Check class of year column
class(NC_energy$`Data Year`)
#Currently a character. Change to date.
NC_energy$`Data Year` <-  as.Date(NC_energy$`Data Year`, format = "%Y")

```

```{r} 
#Load in CEJST data
cejst_data <- read.csv(here("./Data/Raw/CEJST_data.csv"))
#Filter for NC
NC_cejst <- cejst_data %>% 
  filter(cejst_data$State.Territory == "North Carolina")
#Remove the word "County" from the county column
NC_cejst$County.Name <- gsub("\\s*[Cc]ounty", "", NC_cejst$County.Name)
#Find a total county average for relevant columns
counties_summarized <- NC_cejst %>% 
  group_by(County.Name) %>% 
  summarise(percent_black = mean(Percent.Black.or.African.American.alone),
            percent_na = mean(Percent.American.Indian...Alaska.Native),
            percent_asian = mean(Percent.Asian),
            percent_hawaiian = mean(Percent.Native.Hawaiian.or.Pacific),
            percent_two = mean(Percent.two.or.more.races),
            percent_white = mean(Percent.White),
            percent_hispanic = mean(Percent.Hispanic.or.Latino),
            disadvantaged = mean(Percentage.of.tract.that.is.disadvantaged.by.area),
            population = sum(Total.population),
            percent_poverty = mean(Percent.of.individuals.below.200..Federal.Poverty.Line..percentile.),
            PM2.5 = mean(PM2.5.in.the.air))

```

```{r}
#Rename the county column name in the energy df to match the CEJST df
NC_energy <- NC_energy %>% 
  rename("County.Name" = "Plant county name")
#Join CEJST and energy data by county name
NC_joined <- merge(NC_energy, counties_summarized, by = "County.Name", all = FALSE)
```

```{r}
#Save joined data as a file in the processed data folder.
write.csv(NC_joined, row.names = FALSE, 
         file = "./Data/Processed/NC_joined.csv")
```
