---
title: "Messing around with data"
author: "Summer Heschong"
date: "2024-11-13"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
library(dplyr)
library(ggplot2)
library(here)
library(tidyverse)
library(readxl)
library(sf)
library(mapview)
#install.packages('tigris')
library(tigris)
```


```{r load in data}
#check working directory
here()

#load spatial census data
nc_tracts <- tracts(state = 'NC', year = 2020) %>%
  select(GEOID, COUNTYFP, NAME)

#load EJ data
CEJST.data <- read.csv('Data/Raw/CEJST_data.csv')

#load Fiona's processed plant data
nc_plants <- st_read(here('Data/Processed/nc_plants.gpkg'))

```



```{r wrangle data and join to spatial data}
#filter CEJST data for NC
EJ.NC_data <- filter(CEJST.data, State.Territory == 'North Carolina')

#Change spatial columns to factors in both datasets 
EJ.NC_data$Census.tract.2010.ID <- as.factor(EJ.NC_data$Census.tract.2010.ID)
nc_tracts$GEOID <- as.factor(nc_tracts$GEOID)

#Join CEJST data to census spatial data
EJ.NC_sf <- nc_tracts %>%
  left_join(EJ.NC_data, by = c('GEOID'= 'Census.tract.2010.ID')) %>%
  st_as_sf()

```

```{r map data}
#map which counties are classified as disadvantaged

mapview(EJ.NC_sf, zcol = 'Identified.as.disadvantaged',
        layer.name = 'County Disadvantaged Status')

```

```{r add in powerplant locations}
#join nc plant locations and CEJST data and select relevant columns

EJ.NC_plus_plants <- st_join(EJ.NC_sf, nc_plants, join = st_intersects) %>%
  select(Identified.as.disadvantaged, 
         County.Name, 
         Plant.FIPS.county.code, 
         COUNTYFP, 
         Plant.name,
         Plant.primary.fuel.category,
         Percent.Black.or.African.American.alone,
         Percent.American.Indian...Alaska.Native,
         Percent.Asian,
         Percent.Native.Hawaiian.or.Pacific,
         Percent.two.or.more.races,
         Percent.Hispanic.or.Latino,
         Percent.other.races,
         Percent.White,
         Total.population)

``` 

```{r are plant locations significant?}
#run a Chi-square test
observed <- table(EJ.NC_plus_plants$Identified.as.disadvantaged)
expected <- table(EJ.NC_sf$Identified.as.disadvantaged)

chisq_test <- chisq.test(observed, p = expected / sum(expected))
chisq_test

#filter nc_plants data set for the type of energy that is the worst for human health 
nc_unhealthy_plants <- EJ.NC_plus_plants %>%
  filter(Plant.primary.fuel.category== 'OIL' | Plant.primary.fuel.category == 'GAS' | Plant.primary.fuel.category== 'COAL' | Plant.primary.fuel.category=='NUCLEAR' |Plant.primary.fuel.category=='BIOMASS')

#Perform Chi-square test for worst types of energy to live by
observed <- table(nc_unhealthy_plants$Identified.as.disadvantaged)
expected <- table(EJ.NC_sf$Identified.as.disadvantaged)

chisq_test <- chisq.test(observed, p = expected / sum(expected))
chisq_test


```



```{r map data 2.0}
#Map plants and counties together
mapview(EJ.NC_sf, zcol = 'Identified.as.disadvantaged',
        layer.name = 'County Disadvantaged Status') +
  mapview(nc_plants)

```


```{r try to calculate disproportionality ratio}
# find counties with highest number of powerplants
Plant_counties <- na.omit(nc_unhealthy_plants)

# percent poc in powerplant counties
Plant_counties$percent.poc <- 1 - Plant_counties$Percent.White

percent_poc_plant_counties <- Plant_counties %>%
  filter(Total.population > 0) %>%
  mutate(weighted_poc = percent.poc * Total.population) %>%
  summarize(
    total_poc = sum(weighted_poc),
    total_population = sum(Total.population)
  ) %>%
  mutate(total_percent_poc = (total_poc / total_population) * 100) %>%
  print(percent_poc_plant_counties)

# percent poc in NC
EJ.NC_data$percent.poc <- 1 - EJ.NC_data$Percent.White

percent_poc_NC <- EJ.NC_data %>%
  filter(Total.population > 0) %>%
  mutate(weighted_poc = percent.poc * Total.population) %>%
  summarize(
    total_poc = sum(weighted_poc),
    total_population = sum(Total.population)
  ) %>%
  mutate(total_percent_poc = (total_poc / total_population) * 100) %>%
  print(percent_poc_NC)

# calculate disproportionality ratio
disproportionality_ratio <- percent_poc_plant_counties$total_percent_poc / percent_poc_NC$total_percent_poc

#perform Wilcoxon Rank-sum test
wilcox.test(percent_poc_NC$total_percent_poc, percent_poc_plant_counties$total_percent_poc)
```
